### PR TITLE
make sure update-base64 task can use custom json file

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #36

### CODE REVIEW

**Comment by gkatsev** [comment]
Shouldn't custom-json merge into the icon config?

**Comment by thijstriemstra** [comment]
I have a custom `videojs-record-icons.json` file and run:

```
grunt --exclude-default --custom-json=videojs-record-icons.json
```

The only thing `update-base64` needs from the `icons.json` (or `custom-icons.json`) is the font name. Merging the font name from custom-icons.json into icons.json is the same as simply picking the name from custom-icons.json, so I chose this approach. The .woff file that the task loads based on the font name has already been generated in a previous step (called `generate-font`) so no need to merge anything..

**Comment by thijstriemstra** [comment]
ping @gkatsev

**Comment by thijstriemstra** [comment]
Can this be merged and released? Without this change the `--custom-json` option is broken..

**Comment by thijstriemstra** [comment]
ping @gkatsev

**Comment by gkatsev** [comment]
Thanks for your patience!

**Comment by gkatsev** [comment]
available in 3.1.1.

**Pull request merged**
