### PR TITLE
customize font name in example doc

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I suppose another example should be added to demonstrate how to create your own font (for a plugin for example). I'll update PR.

**Comment by gkatsev** [comment]
That would be great, thanks @thijstriemstra

**Comment by thijstriemstra** [comment]
Updated the PR @gkatsev.

**Comment by thijstriemstra** [comment]
ping @gkatsev (can you enable request review feature for this repo as well?).

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
Thanks for your patience, @thijstriemstra.

**Pull request merged**
