### PR TITLE
Feature custom json

### PR DESCRIPTION
**Pull request by ivanovyordan**
- Update material design icons
- Allow icons generation with external configuration

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR. Can you elaborate on what this does and how to use it? Not quite sure just from reading the code.

**Comment by ivanovyordan** [comment]
I need to add more icons to my player and at the same time I want to be able to update the package easily.

So if I need the `remove_red_eye` for example, I can create `custom_icons.json` file:
``` json
{
  "icons": [{
    "name": "visibility",
    "svg": "image/svg/production/ic_remove_red_eye_48px.svg"
  }]
}
```
After that I just need to call `grunt default:../custom_icons.json` and my icon will be added.

**Comment by ivanovyordan** [comment]
Sorry. I just made a new test and it looks my previous merging functions were buggy. It should be OK now.

**Comment by thijstriemstra** [comment]
This looks very useful, any way to prevent duplication of code from this repository is great. My videojs-record plugin also contains code copied from this repository, would be great to get PR this merged and released @gkatsev 

@ivanovyordan can you add documentation to the readme file?

**Comment by ivanovyordan** [comment]
Sure. Will do it in the next few days.

**Comment by thijstriemstra** [comment]
Also, I'm using the usual video.js font + a custom font, both generated by this plugin. So my icons.json only contains a few additional fonts. I think this would be better default behavior (for this PR).

**Comment by gkatsev** [comment]
Had some trouble getting this to work at first with the directions above but got it to work with:
```sh
grunt generate-font:../custom.json update-base64 sass
```
Going to merge this and probably make a separate PR to make it a bit easier to do this. Also, want to write docs for it as well.

**Pull request merged**
