### PR TITLE
don't hardcode font name in grunt task

### PR DESCRIPTION
**Pull request by thijstriemstra**
pull it from icons.json instead

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @gkatsev

**Comment by gkatsev** [comment]
Hey @thijstriemstra. 
Thanks for the PR, looks like a great idea.
Been busy this week with preparations for my demuxed talk next week, so, that's why it's been really quiet on my end.

**Comment by thijstriemstra** [comment]
any update?

**Comment by gkatsev** [comment]
Thanks for your patience, getting to this now!

**Pull request merged**
